### ISSUE TITLE
OpenCv Version

### ISSUE THREAD

**Issue by flapflap** [pukeanddie/aruco-arkit-localizer#1]
Hi,

Wich OpenCV framework did you use?

Thanks

**Comment by danilovdorin** [comment]
For me works 3.4.0 version

**Comment by natwales** [comment]
Unfortunately, the compiled OpenCV lib was not included in this repo. (misuse of Git LFS on my part) But yes, 3.4.0 should work. Note that you will need to rebuild OpenCV with aruco lib from [opencv contrib modules](https://github.com/opencv/opencv_contrib).
