### ISSUE TITLE
#include "opencv2/aruco.hpp" not found.

### ISSUE THREAD

**Issue by DGP13** [pukeanddie/aruco-arkit-localizer#2]
Hi,

Which OpenCV framework did you use?

OpenCV 3.4.0 version in not found aruco.hpp file.

Thanks

**Comment by natwales** [comment]
I thought I had included a compiled version of opencv with aruco as part of this repo. I added it through [git LFS](https://git-lfs.github.com/) but it appears that is missing. If I remember correctly I needed to rebuild OpenCV with aruco from the [contrib modules.](https://github.com/opencv/opencv_contrib) So if you are using a standard openCV build then aruco will be missing.

**Comment by DGP13** [comment]
how to create opencv framework using contrib modules.

**Comment by natwales** [comment]
I'd start by following the instructions on the [contrib modules repo](https://github.com/opencv/opencv_contrib). If you get stuck along the way hit me up.

**Comment by DGP13** [comment]
If you can provide me opencv2.framework or how to create framework files?

**Comment by GipsySh** [comment]
I've built OpenCV with extra modules following the guide https://github.com/opencv/opencv_contrib
But I don't know how create framework now. Can you help me, please?

**Comment by aelarassi** [comment]
@DGP13 , @GipsySh I am using OpenCV2-contrib as a pod, which has all the modules from the OpenCV contrib library.

`pod 'OpenCV2-contrib'`

[OpenCV2-contrib](https://cocoapods.org/pods/OpenCV2-contrib)
